# Generated by Django 4.1.7 on 2023-05-03 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Name', models.CharField(max_length=60)),
                ('Last_Name', models.CharField(max_length=60)),
                ('E_mail', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('Re_password', models.CharField(max_length=50)),
            ],
        ),
    ]
