# Generated by Django 4.1.7 on 2023-05-06 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website1', '0002_rooms'),
    ]

    operations = [
        migrations.AddField(
            model_name='rooms',
            name='Fee',
            field=models.IntegerField(default=0),
        ),
    ]
