# Generated by Django 4.1.7 on 2023-10-08 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website1', '0003_rooms_fee'),
    ]

    operations = [
        migrations.RenameField(
            model_name='register',
            old_name='First_Name',
            new_name='Name',
        ),
        migrations.RemoveField(
            model_name='register',
            name='Last_Name',
        ),
        migrations.RemoveField(
            model_name='register',
            name='Re_password',
        ),
    ]
