# Generated by Django 4.1.7 on 2023-11-10 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website1', '0004_rename_first_name_register_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('phone', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='Register',
        ),
        migrations.DeleteModel(
            name='Rooms',
        ),
    ]
