# Generated by Django 4.1.7 on 2023-11-13 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website1', '0007_rename_email_customer_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rooms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Room_No', models.CharField(max_length=50)),
                ('Room_Type', models.CharField(max_length=50)),
                ('Room_Price', models.CharField(max_length=50)),
                ('Room_Status', models.CharField(max_length=50)),
            ],
        ),
    ]
