# Generated by Django 4.1.7 on 2023-11-13 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website1', '0008_rooms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rooms',
            name='Room_Status',
            field=models.BooleanField(default=False),
        ),
    ]
