# Generated by Django 4.1.7 on 2023-11-13 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website1', '0010_alter_rooms_room_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rooms',
            name='Room_Status',
        ),
        migrations.AlterField(
            model_name='rooms',
            name='Room_Type',
            field=models.CharField(choices=[('DELUXE', 'DELUXE'), ('LUXURY', 'LUXURY'), ('PREMIUM', 'PREMIUM')], max_length=50),
        ),
    ]
