# Generated by Django 4.1.7 on 2023-11-13 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website1', '0011_remove_rooms_room_status_alter_rooms_room_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Booked', 'Booked'), ('Cancelled', 'Cancelled')], max_length=50)),
                ('Room_No', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website1.rooms')),
            ],
        ),
    ]
