# Generated by Django 4.1.7 on 2023-12-21 15:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('website1', '0015_remove_booking_id_booking_book_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='Customer_Name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
