# Generated by Django 4.1.7 on 2023-12-21 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website1', '0016_alter_booking_customer_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='book_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
