# Generated by Django 4.1.7 on 2023-12-21 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website1', '0017_alter_booking_book_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='rooms',
            name='capacity',
            field=models.IntegerField(default=3),
        ),
    ]
