# Generated by Django 4.1.7 on 2023-12-29 07:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('website1', '0018_rooms_capacity'),
    ]

    operations = [
        migrations.CreateModel(
            name='maintainanceRequest',
            fields=[
                ('request_id', models.AutoField(primary_key=True, serialize=False)),
                ('issue', models.CharField(max_length=350)),
                ('Customer_Name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('Room_No', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='website1.rooms')),
            ],
        ),
    ]
