# Generated by Django 4.1.7 on 2023-12-29 07:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('website1', '0019_maintainancerequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintainancerequest',
            name='date_of_request',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
