# Generated by Django 4.1.7 on 2024-01-01 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website1', '0023_remove_customer_email_remove_customer_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='dp',
            field=models.ImageField(blank=True, upload_to='profile_pics/'),
        ),
    ]
