# Generated by Django 4.1.7 on 2024-01-01 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website1', '0024_customer_dp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='dp',
            field=models.ImageField(blank=True, upload_to='website1/profile_pics'),
        ),
    ]
