# Generated by Django 4.1.7 on 2024-01-01 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website1', '0025_alter_customer_dp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='dp',
            field=models.ImageField(blank=True, upload_to='profile_pics/'),
        ),
    ]
