# Generated by Django 4.1.7 on 2024-01-01 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website1', '0026_alter_customer_dp'),
    ]

    operations = [
        migrations.AddField(
            model_name='rooms',
            name='status',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='website1.booking'),
        ),
    ]
