# Generated by Django 4.1.7 on 2024-01-01 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website1', '0027_rooms_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rooms',
            name='status',
        ),
    ]
