# Generated by Django 4.1.7 on 2024-01-09 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website1', '0028_remove_rooms_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='Room_No',
        ),
        migrations.RemoveField(
            model_name='maintainancerequest',
            name='Room_No',
        ),
        migrations.RemoveField(
            model_name='rooms',
            name='id',
        ),
        migrations.AddField(
            model_name='rooms',
            name='room_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
        ),
    ]
