# Generated by Django 4.1.7 on 2024-01-09 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website1', '0029_remove_booking_room_no_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='Room_No',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='website1.rooms'),
        ),
        migrations.AddField(
            model_name='maintainancerequest',
            name='Room_No',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='website1.rooms'),
        ),
    ]
