# Generated by Django 4.1.7 on 2024-01-09 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website1', '0030_booking_room_no_maintainancerequest_room_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rooms',
            name='room_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
