# Generated by Django 4.1.7 on 2024-02-03 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website1', '0032_alter_rooms_room_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('item_id', models.AutoField(primary_key=True, serialize=False)),
                ('item_name', models.CharField(max_length=50)),
                ('item_type', models.CharField(choices=[('Electronics', 'Electronics'), ('Furniture', 'Furniture'), ('Stationary', 'Stationary'), ('Grocery', 'Grocery')], max_length=50)),
                ('item_price', models.CharField(max_length=50)),
                ('item_quantity', models.IntegerField(default=1)),
            ],
        ),
    ]
