# Generated by Django 4.1.7 on 2024-02-14 16:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('website1', '0033_inventory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('notice_id', models.AutoField(primary_key=True, serialize=False)),
                ('notice', models.TextField()),
                ('file', models.FileField(blank=True, null=True, upload_to='notices/')),
                ('date_of_notice', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
