# Generated by Django 4.1.7 on 2024-03-21 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website1', '0034_notice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('Booked', 'Booked'), ('Not Booked', 'Not Booked')], default='Not Booked', max_length=50),
        ),
    ]
